### ISSUE TITLE
Should we move this repo and if so, where to?

### ISSUE THREAD

**Issue by olizilla** [arewedistributedyet/arewedistributedyet#25]
We want this to be a common ground for all p2p implementors and browser developers to track the pain points and progress in bringing p2p protocols in to the browser.

This particular site started as an IPFS project and was intended from the start to catalog more than just IPFS issues. If people feel like the repo and issues should live somewhere else, then please say!

Already offered is
- https://github.com/mozilla/dweb

I'd like to start this off as a discussion. If no one cares enough to write a few line sentences about it, then I'll close this and we can move on. If it surfaces a lot of strong feelings then it's worth talking about, and once people have had time to state their preferences, hopefully we can reach a consensus, or boil it down to a vote if necessary.

**Comment by lidel** [comment]
AFAIK the only problem with this repo is `/ipfs-shipyard` in the URL. Sends wrong message.

Perhaps moving it to a vendor-agnostic org would be a better approach? 

    https://github.com/<?>/arewedistributedyet 

IMO a separate org would simplify things and make it very clear that it is a community effort.

To make things even less confusing, we could re-use the name for org and go with:
https://github.com/arewedistributedyet/arewedistributedyet

Thoughts?

**Comment by pfrazee** [comment]
Agree with @lidel

**Comment by karissa** [comment]
Agree with @lidel

**Comment by lidel** [comment]
1. [x] created org under https://github.com/arewedistributedyet
1. [ ] move this repo under `/arewedistributedyet` org
   - i am looking into this right now, will post updates later
1. [ ] ensure CI setup still works under new org
1. [ ] invite everyone from "Re: Decentralized Web 2018 Builders Day Browser Followup" thread to to the org

**Comment by Gozala** [comment]
We also talked about possibility of creating a w3c interest group. I'm not sure what that exactly allows but I wonder if that could allow us to have repo like https://github.com/whatwg/dweb which I think would send a stronger message.

I will try to find more about this and post back here. Otherwise 👍 on https://github.com/arewedistributedyet

**Comment by Gozala** [comment]
Just read through the https://whatwg.org/working-mode and it seems they suggest incubation outside of whatwg group so I retract my above suggestion

> As described above, the criteria for inclusion in a WHATWG standard is rather strict. In the initial stages of feature development for the web platform, such widespread implementer support is often not available, or the shape of a feature is not yet clear enough for implementers to feel comfortable pledging their support.
>
> In such scenarios we anticipate features will be “incubated” outside of WHATWG standards. This could be in a variety of venues, such as:
>
> - Another standards organization
>
> - A personal document or GitHub repository
>
> - A pull request to a WHATWG standard, with the understanding it will not be merged until the criteria above are met
>
> - A document hosted by the WHATWG, but not under the spec.whatwg.org subdomain and not titled “Living Standard”
>
>>    The CanvasColorSpace proposal is being incubated on the WHATWG Wiki. 
>
> In all cases, features that hope to graduate to a WHATWG standard should strive to follow the above guidelines, gather appropriate implementer commitments, and have corresponding tests.
>
> Additionally, those maintaining such proposals should try to involve the WHATWG community, for example by filing an issue on the standard they anticipate eventually becoming a part of.

**Comment by lidel** [comment]
Looks like everyone is ok with move to https://github.com/arewedistributedyet org.

I'll go over move list (https://github.com/ipfs-shipyard/arewedistributedyet/issues/25#issuecomment-411730739) today and post update when done.

**Comment by Gozala** [comment]
Can we close this since this already happened ?

**Comment by lidel** [comment]
I am waiting for CI to be restored in https://github.com/ipfs/testing/issues/126. 
Will close as soon that lands.

**Comment by VictorBjelkholm** [comment]
CI has now been restored :) The user @ImmutableJenkins would need to have `write` access to the repository if you want the Status things to show up in commits and PRs. The user only has `Status`permission in the token we're using so even if compromised, it won't be able to actually write to the repository.

**Comment by lidel** [comment]
It should be enough for now, thank you @VictorBjelkholm !
